"""DeepBrain Memory Provider — page-based SQLite brain for Leaper Agent.

Schema:
    pages(slug TEXT PK, title TEXT, namespace TEXT, content TEXT, updated_at TEXT)
    chunks(id INTEGER PK, page_slug TEXT, content TEXT)

Recall uses LIKE keyword search (no vector index in v0.7.0).

Activated by setting ``memory.provider: deepbrain`` in leaper.yaml / config.yaml,
or via ``HERMES_MEMORY_PROVIDER=deepbrain``.
"""

from __future__ import annotations

import json
import logging
import os
import re
import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agent.memory_provider import MemoryProvider

logger = logging.getLogger(__name__)

_TOOL_RECALL = "brain_recall"
_TOOL_LEARN = "brain_learn"


class DeepBrainMemoryProvider(MemoryProvider):
    """SQLite-backed memory provider using a page/chunk data model.

    Pages represent knowledge articles. Chunks are searchable sub-fragments
    generated by splitting page content at sentence boundaries.

    Both ``brain_recall`` and ``brain_learn`` are exposed as LLM tools.
    """

    @property
    def name(self) -> str:
        return "deepbrain"

    def __init__(self) -> None:
        self._conn: sqlite3.Connection | None = None
        self._lock = threading.Lock()
        self._db_path: str = ""
        self._initialized = False

    # ── MemoryProvider lifecycle ───────────────────────────────────────────────

    def is_available(self) -> bool:
        return True

    def initialize(self, session_id: str, **kwargs) -> None:
        leaper_home = kwargs.get("hermes_home", str(Path.home() / ".leaper"))
        self._db_path = os.environ.get(
            "DEEPBRAIN_DB",
            str(Path(leaper_home) / "brain.db"),
        )
        Path(self._db_path).parent.mkdir(parents=True, exist_ok=True)
        self._conn = sqlite3.connect(self._db_path, check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        self._create_schema()
        self._initialized = True
        logger.info("DeepBrain memory provider loaded (db=%s)", self._db_path)

    def system_prompt_block(self) -> str:
        return (
            "## DeepBrain Knowledge Store\n"
            "You have access to a persistent knowledge base. "
            "Use `brain_recall` to search for relevant past knowledge before answering complex questions. "
            "Use `brain_learn` to store important facts, user preferences, or decisions for future recall."
        )

    def prefetch(self, query: str, *, session_id: str = "") -> str:
        if not self._initialized or not query.strip():
            return ""
        results = self._recall(query, top_k=5)
        if not results:
            return ""
        lines = ["[DeepBrain — Recalled Knowledge]"]
        for i, r in enumerate(results, 1):
            snippet = r["content"][:200].replace("\n", " ")
            lines.append(f"{i}. [{r['namespace']}] {snippet}")
        return "\n".join(lines)

    def sync_turn(self, user_content: str, assistant_content: str, *, session_id: str = "") -> None:
        if not self._initialized:
            return

        def _store():
            try:
                combined = f"User: {user_content}\nAssistant: {assistant_content}"
                if len(combined.split()) > 20:
                    stamp = _now_iso()[:16].replace(":", "").replace("-", "").replace("T", "_")
                    self._learn_page(
                        slug=f"conv_{stamp}",
                        title=_truncate(user_content, 60),
                        namespace="experience",
                        content=combined[:1000],
                    )
            except Exception as exc:
                logger.debug("DeepBrain sync_turn error: %s", exc)

        threading.Thread(target=_store, daemon=True).start()

    def get_tool_schemas(self) -> list[dict[str, Any]]:
        return [
            {
                "name": _TOOL_RECALL,
                "description": (
                    "Search DeepBrain for relevant knowledge from past conversations and stored facts. "
                    "Use before answering complex questions or when the user references prior context."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "Keywords or phrase to search for",
                        },
                        "top_k": {
                            "type": "integer",
                            "description": "Maximum number of results to return (default: 5)",
                            "default": 5,
                        },
                        "namespace": {
                            "type": "string",
                            "description": "Filter by namespace: 'experience', 'workspace', 'user', 'default'",
                        },
                    },
                    "required": ["query"],
                },
            },
            {
                "name": _TOOL_LEARN,
                "description": (
                    "Store new knowledge in DeepBrain for future recall. "
                    "Use for important facts, user preferences, key decisions, or reusable patterns."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "content": {
                            "type": "string",
                            "description": "The knowledge content to store",
                        },
                        "title": {
                            "type": "string",
                            "description": "Short descriptive title (auto-generated if omitted)",
                        },
                        "namespace": {
                            "type": "string",
                            "description": "Namespace for organizing knowledge (default: 'default')",
                            "default": "default",
                        },
                    },
                    "required": ["content"],
                },
            },
        ]

    def handle_tool_call(self, tool_name: str, args: dict[str, Any], **kwargs) -> str:
        if tool_name == _TOOL_RECALL:
            return self._handle_recall(args)
        if tool_name == _TOOL_LEARN:
            return self._handle_learn(args)
        raise NotImplementedError(f"Unknown tool: {tool_name}")

    def shutdown(self) -> None:
        if self._conn:
            try:
                self._conn.close()
            except Exception:
                pass
            self._conn = None
            logger.info("DeepBrain: database connection closed")

    def get_config_schema(self) -> list[dict[str, Any]]:
        return [
            {
                "key": "db_path",
                "description": "Path to the DeepBrain SQLite database",
                "required": False,
                "default": "~/.leaper/brain.db",
                "env_var": "DEEPBRAIN_DB",
            }
        ]

    # ── Tool handlers ─────────────────────────────────────────────────────────

    def _handle_recall(self, args: dict[str, Any]) -> str:
        query = args.get("query", "").strip()
        if not query:
            return json.dumps({"error": "query cannot be empty"})
        top_k = max(1, int(args.get("top_k", 5)))
        namespace = args.get("namespace") or None
        results = self._recall(query, top_k=top_k, namespace=namespace)
        if not results:
            return json.dumps({"results": [], "message": "No matching entries found."})
        return json.dumps({
            "results": [
                {
                    "title": r["title"],
                    "content": r["content"][:500],
                    "namespace": r["namespace"],
                    "updated_at": r["updated_at"],
                }
                for r in results
            ],
            "total": len(results),
        })

    def _handle_learn(self, args: dict[str, Any]) -> str:
        content = args.get("content", "").strip()
        if not content:
            return json.dumps({"error": "content cannot be empty"})
        title = args.get("title", "").strip() or _truncate(content, 60)
        namespace = args.get("namespace", "default")
        slug = _make_slug(title)
        self._learn_page(slug=slug, title=title, namespace=namespace, content=content)
        return json.dumps({"stored": True, "slug": slug, "namespace": namespace})

    # ── SQLite operations ─────────────────────────────────────────────────────

    def _create_schema(self) -> None:
        with self._lock:
            cur = self._conn.cursor()
            cur.executescript("""
                CREATE TABLE IF NOT EXISTS pages (
                    slug        TEXT PRIMARY KEY,
                    title       TEXT NOT NULL DEFAULT '',
                    namespace   TEXT NOT NULL DEFAULT 'default',
                    content     TEXT NOT NULL DEFAULT '',
                    updated_at  TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS chunks (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    page_slug   TEXT NOT NULL REFERENCES pages(slug) ON DELETE CASCADE,
                    content     TEXT NOT NULL
                );

                CREATE INDEX IF NOT EXISTS idx_chunks_page      ON chunks(page_slug);
                CREATE INDEX IF NOT EXISTS idx_pages_namespace  ON pages(namespace);
                CREATE INDEX IF NOT EXISTS idx_pages_updated    ON pages(updated_at DESC);
            """)
            self._conn.commit()

    def _recall(self, query: str, top_k: int = 5, namespace: str | None = None) -> list[dict]:
        if not self._conn or not query.strip():
            return []
        terms = [t for t in re.split(r"\s+", query.strip()) if len(t) >= 2]
        if not terms:
            return []

        with self._lock:
            cur = self._conn.cursor()
            like_parts = " OR ".join("p.content LIKE ?" for _ in terms)
            params: list[Any] = [f"%{t}%" for t in terms]
            ns_clause = ""
            if namespace:
                ns_clause = " AND p.namespace = ?"
                params.append(namespace)
            params.append(top_k)
            cur.execute(
                f"""
                SELECT p.slug, p.title, p.namespace, p.content, p.updated_at
                FROM pages p
                WHERE ({like_parts}){ns_clause}
                ORDER BY p.updated_at DESC
                LIMIT ?
                """,
                params,
            )
            return [dict(r) for r in cur.fetchall()]

    def _learn_page(self, slug: str, title: str, namespace: str, content: str) -> None:
        if not self._conn:
            return
        now = _now_iso()
        with self._lock:
            cur = self._conn.cursor()
            cur.execute(
                """
                INSERT INTO pages(slug, title, namespace, content, updated_at)
                VALUES (?, ?, ?, ?, ?)
                ON CONFLICT(slug) DO UPDATE SET
                    title      = excluded.title,
                    namespace  = excluded.namespace,
                    content    = excluded.content,
                    updated_at = excluded.updated_at
                """,
                (slug, title, namespace, content, now),
            )
            cur.execute("DELETE FROM chunks WHERE page_slug = ?", (slug,))
            chunks = _split_chunks(content)
            cur.executemany(
                "INSERT INTO chunks(page_slug, content) VALUES (?, ?)",
                [(slug, c) for c in chunks],
            )
            self._conn.commit()


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _truncate(text: str, n: int) -> str:
    return text[:n].rstrip() + ("…" if len(text) > n else "")


def _make_slug(text: str) -> str:
    slug = re.sub(r"[^\w一-鿿]+", "_", text.lower().strip())
    date_part = _now_iso()[:10].replace("-", "")
    return f"{slug[:50]}_{date_part}".strip("_")


def _split_chunks(text: str, max_len: int = 300) -> list[str]:
    sentences = re.split(r"(?<=[.。!?！？\n])\s*", text.strip())
    chunks: list[str] = []
    current = ""
    for sentence in sentences:
        sentence = sentence.strip()
        if not sentence:
            continue
        if len(current) + len(sentence) <= max_len:
            current = f"{current} {sentence}".strip()
        else:
            if current:
                chunks.append(current)
            current = sentence[:max_len]
    if current:
        chunks.append(current)
    return chunks or [text[:max_len]]
